### ISSUE TITLE
Implement the server functionality that allows sign in

### ISSUE THREAD

**Issue by gorkemmulayim** [Bil495/Not2Do#2]
Implement a HTTP post method that allows sign in. The server should receive parameters in the request body, in the JSON format. Parameters sent to the server contain id, password, name and surname of the user.

**Comment by uyarburak** [comment]
**Sign-Up**
----
  Register the given user and returns a token for the user.

* **URL**

  /api/v1/sign_up

* **Method:**

  `POST`

* **Data Params**

    ```javascript
    {
        username : [string],
        password : [alphanumeric],
        email : [alphanumeric],
        name : [string],
        surname : [string]
    }
  ```

* **Success Response:**

  * **Code:** 200 <br />
    **Content:** `{ id : 12, token : "abcsd832bdf3" }`
 
* **Error Response:**

  * **Code:** 401 UNAUTHORIZED <br />
    **Content:** `{ error : "Email already using." }`

  OR

  * **Code:** 401 UNAUTHORIZED <br />
    **Content:** `{ error : "Username already taken." }`

* **Sample Call:**

  ```javascript
    $.ajax({
      url: "/api/v1/sign_up",
      data:     {
        username : username,
        password : password,
        email : email,
        name : name,
        surname : surname
    },
      type : "POST",
      success : function(r) {
        console.log(r);
      }
    });
  ```
