### ISSUE TITLE
Implement the server functionality that allows log in

### ISSUE THREAD

**Issue by gorkemmulayim** [Bil495/Not2Do#3]
Implement a HTTP post method that allows log in. The server should receive parameters in the request body, in the JSON format. Parameters sent to the server contain id and password. The server should return the appropriate result depending on the status of log in action.

**Comment by uyarburak** [comment]
**Login**
----
  Returns a token for the user.

* **URL**

  /api/v1/login

* **Method:**

  `POST`

* **Data Params**

    ```javascript
    {
        username : [string],
        password : [alphanumeric]
    }
  ```

* **Success Response:**

  * **Code:** 200 <br />
    **Content:** `{ id : 12, token : "abcsd832bdf3" }`
 
* **Error Response:**

  * **Code:** 404 NOT FOUND <br />
    **Content:** `{ error : "Username doesn't exist" }`

  OR

  * **Code:** 401 UNAUTHORIZED <br />
    **Content:** `{ error : "Wrong password" }`

* **Sample Call:**

  ```javascript
    $.ajax({
      url: "/api/v1/login",
      data: { username: username, password: pass},
      type : "POST",
      success : function(r) {
        console.log(r);
      }
    });
  ```
